// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  faq: dynamic(() => import("./Faq")),
  hero: dynamic(() => import("./Hero")),
  home_blog_section: dynamic(() => import("./HomeBlogSection")),
  rich_text: dynamic(() => import("./BlogContent")),
};
